version: "3.8"
services:
  mysql:
    container_name: darkwood-crypto-tracker-mysql
    hostname: darkwood-crypto-tracker-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/db:/var/lib/mysql
